spring.profiles.include: mysql,redis

server:
  port: 8088
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    context-path: /
# 中文编码
spring:
  http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.jdcloud.medicine.mall.domain
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql

#============配置日志===============
logging:
  config: classpath:logback.xml

cms:
  web:
    domain: http://localhost:8088



#============阿里云OSS配置=================
oss:
  aliyun:
    endpoint: https://oss-cn-qingdao.aliyuncs.com
    accessKeyId: LTAI4FnHixH9ffmT2i3D9CtL
    ccessKeySecret: g3JfvahPWon5iWw8LxercdX5A8L4ZJ
    bucketName: taochonghui
    picLocation: yw/image





